export interface Lead {
  id: number;
  fname: string;
  mname: string;
  lname: string;
  email: string;
  phone: string;
  mobile: string;
  nationality: string;
  address: string;
  dob: string;
  gender: string;
  id_number: string;
  id_expiry: string;
  country_interest: string;
  service_interest: string;
  market_source: string;
  appointment: string;
  followup: string;
  folowuptime: string;
  followupstat: number;
  enquiry: string;
  convet: string;
  priority: string;
  status: string;
  regdate: string;
  assignTo: number;
  branch: number;
  region: number;
  payTotal: number;
  paidYet: number;
  payBalance: number;
  lead_remark: string;
  created: string;
  lead_quality: string;
  dmEmployeeByASSIGNTo?: { id: number; name: string };
  dmEmployeeByCoUNSILOR?: { id: number; name: string };
  dmBranch?: { id: number; name: string };
}
